name: Enhancement
description: New feature or enhancement
title: "[New Feature]: "
labels: [enhancement, triage]
body:
- type: markdown
  attributes:
    value: |
      - Write a descriptive feature/enhancement title above.
      - Search [open](https://github.com/AlchemyViewer/Alchemy/issues?q=is%3Aopen+label%3Aenhancement+is%3Aissue) feature/enhancement requests to ensure that the feature has not already been requested.

- type: textarea
  attributes:
    label: Environment
    description: About Alchemy Text
    placeholder: ex. Alchemy Test 7.1.3.240191747 (64bit) ...
  validations:
    required: true

- type: textarea
  attributes:
    label: Description
    description: What does this feature/enhancement do? Why is it needed? Include screenshots to illustrate how it should function if possible!
  validations:
    required: true
